server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kamel_loewe_kind
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kamel.board
