CREATE TABLE IF NOT EXISTS category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_type VARCHAR(20) NOT NULL,
    name       VARCHAR(50) NOT NULL,
    CONSTRAINT uq_category_board_type_name UNIQUE (board_type, name)
);

CREATE TABLE IF NOT EXISTS board (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_type VARCHAR(20) NOT NULL,
    category_id BIGINT NOT NULL,
    author      VARCHAR(20) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    title       VARCHAR(200) NOT NULL,
    content     TEXT NOT NULL,
    view_count  INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NULL,
    CONSTRAINT fk_board_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE IF NOT EXISTS comment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id  BIGINT NOT NULL,
    author     VARCHAR(20) NOT NULL,
    content    VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comment_board FOREIGN KEY (board_id) REFERENCES board(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS attachment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id         BIGINT,
    original_filename VARCHAR(255) NOT NULL,
    stored_path       VARCHAR(255) NOT NULL,
    content_type      VARCHAR(100),
    size              BIGINT NOT NULL DEFAULT 0,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attachment_board FOREIGN KEY (board_id) REFERENCES board(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS board_notice (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id         BIGINT NOT NULL UNIQUE,
    meeting_at       TIMESTAMP NOT NULL,
    location         VARCHAR(255) NOT NULL,
    book             VARCHAR(255) NOT NULL,
    publisher        VARCHAR(255) NOT NULL,
    page_start       INT NOT NULL DEFAULT 0,
    page_end         INT NOT NULL DEFAULT 0,
    fee              BIGINT,
    fee_description  VARCHAR(255),
    CONSTRAINT fk_board_notice_board FOREIGN KEY (board_id) REFERENCES board(id) ON DELETE CASCADE
);
